[package]
name = "infinity_loop_android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infinity_loop = { path = "../.." }
glutin = "0.30"
winit = { version = "0.28", features = ["android-game-activity"] }
raw-window-handle = "0.5"
#glam = "0.20"
#android-activity = {version = "0.4", features = [ "game-activity" ]}
#ndk-context = "0.1"
#ndk-sys = "0.4.0"
#jni = "0.21"
log = "0.4"
android_logger = "0.13"

[package.metadata.android]
build_targets = ["aarch64-linux-android"]#armv7-linux-androideabi",
apk_name = "infinity_loop"

[[package.metadata.android.uses_feature]]
required = true
version = 0x00030000

[package.metadata.android.application]
isGame = true
label = "Infinity Loop"

[package.metadata.android.application.activity]
immersive = true
orientation = "userPortrait"