# You must change these to your own details.
[package]
name = "infinity_loop"
description = "The Infinity Loop game as web app"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[profile.release]
lto = true

[build-dependencies]
bytemuck = {version = "1.5.1", features = ["derive"]}
glam = {version = "0.15", features = ["bytemuck"]}
anyhow = "1.0.40"

[dependencies]




