# You must change these to your own details.
[package]
name = "infinity_loop"
description = "The Infinity Loop game as web app"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[profile.release]
lto = true

[build-dependencies]
glam = "0.20"
anyhow = "1.0.40"

[dependencies]
miniquad = "0.3.0-alpha"
glam = "0.20"
fastrand = "1.5"
smallbitset = "0.3.0"
lazy_static = "1.4"
enum-iterator = "0.7"
miniserde = "0.1"

