# You must change these to your own details.
[package]
name = "infinity_loop"
description = "The Infinity Loop game as web app"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[features]
#default = ["wee_alloc"]

[target."cfg(debug)".dependencies]
console_error_panic_hook = "0.1.5"

[build-dependencies]
bytemuck = {version = "1.5.1", features = ["derive"]}
glam = {version = "0.15", features = ["bytemuck"]}
anyhow = "1.0.40"

[dependencies]
wasm-bindgen = "0.2"
fastrand = "1.4"
smallbitset = "0.3"
lazy_static = "1.4"
css-color-parser = "0.1"
enum-iterator = "0.6"
glam = {version = "0.15"}
wee_alloc = { version = "0.4", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
  'console',
  'MouseEvent',
  'Performance',
  'CssStyleDeclaration',
  'HtmlSpanElement'
]



