# You must change these to your own details.
[package]
name = "infinity_loop"
description = "The Infinity Loop game as web app"
version = "0.1.0"
authors = ["sidit77 <sidit77@gmail.com>"]
categories = ["wasm"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[features]
#default = ["wee_alloc"]

[target."cfg(debug)".dependencies]
console_error_panic_hook = "0.1.5"

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3.51"
glam = {version = "0.15.2"}
wee_alloc = { version = "0.4.2", optional = true }

[dependencies.web-sys]
version = "0.3.22"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Node',
  'Window',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlUniformLocation',
  'WebGlProgram',
  'WebGlShader',
  'console',
  'MouseEvent',
]



