[package]
name = "infinity_loop_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
infinity_loop = { path = "../.." }
web-sys = { version="0.3", features=[
    "console",
    "AddEventListenerOptions",
    "CssStyleDeclaration",
    "BeforeUnloadEvent",
    "Document",
    "DomRect",
    "Element",
    "Event",
    "EventTarget",
    "FocusEvent",
    "HtmlCanvasElement",
    "HtmlElement",
    "KeyboardEvent",
    "MediaQueryList",
    "MediaQueryListEvent",
    "MouseEvent",
    "Node",
    "PointerEvent",
    "WebGl2RenderingContext",
    "Window",
    "WheelEvent"
]}
wasm-bindgen = "0.2"
log = "0.4"
console_log = "0.2"
console_error_panic_hook = "0.1"

# if i remove this the app stops working, whyyyyyyyyyyyyyyyyyy
winit = "0.27"