[package]
name = "infinity_loop_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
infinity_loop = { path = "../.." }
winit = "0.27"
wasm-bindgen = "0.2"
log = "0.4"
console_log = "0.2"
web-sys = { version="0.3", features=["Window", "HtmlCanvasElement", "WebGl2RenderingContext", "Document"]}
console_error_panic_hook = "0.1"