[package]
name = "infinity_loop_desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "infinity_loop"
path = "src/main.rs"

[dependencies]
infinity_loop = { path = "../.." }
glutin = "0.28"
log = "0.4"
env_logger = "0.9"