#![allow(dead_code)]
//This file is autogenerated
pub const VERTEX_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/meshes.bin"));
pub const QUAD: std::ops::Range<i32> = 0..6;
pub const HEXAGON: std::ops::Range<i32> = 6..18;
pub const MODEL1: std::ops::Range<i32> = 18..210;
pub const MODEL2: std::ops::Range<i32> = 210..396;
pub const MODEL3: std::ops::Range<i32> = 396..402;
pub const MODEL4: std::ops::Range<i32> = 402..774;
pub const MODEL5: std::ops::Range<i32> = 774..1518;
pub const MODEL6: std::ops::Range<i32> = 1518..1704;
pub const MODEL7: std::ops::Range<i32> = 1704..2262;
