//This file is autogenerated
pub const VERTEX_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/meshes.bin"));
pub const HEXAGON: std::ops::Range<i32> = 0..12;
pub const MODEL1: std::ops::Range<i32> = 12..210;
